import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  external: [
    "@agentclaw/types",
    "@agentclaw/core",
    "@agentclaw/providers",
    "@agentclaw/tools",
    "@agentclaw/memory",
    "fastify",
    "@fastify/cors",
    "@fastify/websocket",
    "croner",
    "better-sqlite3",
    "grammy",
    "dotenv",
    "mammoth",
    "xlsx",
    "@sentry/node",
    "ws",
    "@fastify/static",
    "@wecom/aibot-node-sdk",
    "node-edge-tts",
    "sherpa-onnx-node",
    /^sherpa-onnx-/,
    "silk-wasm",
    "opencc-js",
    "pdf-parse",
    "@mozilla/readability",
    "linkedom",
    "turndown",
  ],
});
